# Generated by Django 2.0.7 on 2018-07-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'analyst'), (2, 'associate'), (3, 'quant')], default=0, null=True),
        ),
    ]
