# Generated by Django 2.0.7 on 2018-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180721_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='tagline',
            field=models.CharField(default='', max_length=255),
        ),
    ]
