# Generated by Django 2.0.7 on 2018-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_reportcategory_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_preferences',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'get all updates on a daily basis'), (1, 'only for big changes in the portfolio'), (2, 'at the end of the semester'), (3, 'never')], default=0, null=True),
        ),
    ]
