# Generated by Django 2.0.7 on 2018-07-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'assets',
                'ordering': ('ticker',),
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started', models.DateTimeField()),
                ('last_rebalanced', models.DateTimeField()),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('minimum_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'funds',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funds.Fund')),
            ],
            options={
                'verbose_name_plural': 'portfolios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Rebalance',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Portfolio')),
            ],
            options={
                'verbose_name_plural': 'weights',
                'ordering': ('asset',),
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='optimization_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Optimization'),
        ),
        migrations.AddField(
            model_name='fund',
            name='rebalance_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Rebalance'),
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ManyToManyField(to='funds.Portfolio'),
        ),
    ]
