# Generated by Django 2.0.7 on 2018-07-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
