# Generated by Django 2.0.7 on 2018-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_optimization_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='objective',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'maximize returns'), (1, 'minimize volatility')], null=True),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='key',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'mvo')], null=True),
        ),
    ]
