# Generated by Django 2.0.7 on 2018-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20180714_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date_allocated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
