# Generated by Django 2.0.7 on 2018-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_weight_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
