# Generated by Django 2.0.7 on 2018-07-16 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_asset_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 21, 50, 55, 163906)),
        ),
    ]
