# Generated by Django 2.0.7 on 2018-07-16 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_auto_20180715_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'hold'), (1, 'buy'), (2, 'sell')], default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 22, 4, 7, 587043)),
        ),
    ]
