# Generated by Django 2.0.7 on 2018-07-16 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_auto_20180715_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 22, 5, 7, 980801)),
        ),
    ]
