# Generated by Django 2.0.7 on 2018-07-25 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0015_auto_20180718_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioStatistics',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.FloatField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.Portfolio')),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 8, 1, 59, 929134)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='objective',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'buy and hold'), (1, 'maximize returns'), (2, 'minimize volatility')], null=True),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='key',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'benchmark'), (1, 'mvo')], null=True),
        ),
    ]
