# Generated by Django 2.0.7 on 2018-07-25 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_auto_20180725_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 8, 2, 15, 297429)),
        ),
    ]
