# Generated by Django 2.0.7 on 2018-08-04 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_auto_20180725_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='value',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='value_high',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='value_low',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 4, 16, 0, 39, 210317)),
        ),
    ]
