# Generated by Django 2.0.7 on 2018-08-09 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0019_auto_20180809_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coupled_asset',
            field=models.ManyToManyField(blank=True, related_name='_asset_coupled_asset_+', to='funds.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 19, 36, 38, 161664)),
        ),
    ]
