# Generated by Django 2.0.7 on 2018-08-09 23:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0020_auto_20180809_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='coupled_asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='coupled_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 19, 40, 29, 165460)),
        ),
    ]
