# Generated by Django 2.0.7 on 2018-08-13 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0021_auto_20180809_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='coupled_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 13, 17, 14, 40, 597800)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value_high',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value_low',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
