# Generated by Django 2.0.7 on 2018-08-16 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0023_auto_20180816_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 15, 14, 3, 364158)),
        ),
    ]
