# Generated by Django 2.0.7 on 2018-08-16 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0025_auto_20180816_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weight',
            name='current_weight',
            field=models.BooleanField(default=False),
        ),
    ]
