# Generated by Django 2.0.7 on 2018-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0026_auto_20180816_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='current_weight',
            field=models.BooleanField(default=True),
        ),
    ]
