# Generated by Django 2.0.7 on 2018-08-18 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0027_auto_20180816_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('date_observed', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'absolute'), (1, 'relative')], default=0)),
                ('value', models.FloatField(default=0)),
                ('sensitivty', models.FloatField(default=0)),
                ('primary_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_asset', to='funds.Asset')),
                ('secondary_asset', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_asset', to='funds.Asset')),
            ],
            options={
                'verbose_name_plural': 'Views',
                'ordering': ('name',),
            },
        ),
    ]
