# Generated by Django 2.0.7 on 2018-08-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0028_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='primary_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_asset', to='funds.Asset'),
        ),
        migrations.AlterField(
            model_name='view',
            name='secondary_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_asset', to='funds.Asset'),
        ),
    ]
