# Generated by Django 2.0.7 on 2018-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0031_auto_20180826_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliostatistics',
            name='sharpe_ratio',
            field=models.FloatField(default=0),
        ),
    ]
